### ISSUE TITLE
Option to reorder elements

### ISSUE THREAD

**Issue by pointydev** [ravindUwU/firefox-refined-findbar#1]
Hey there,

First of all, thanks for making this stylesheet, it's made my transition from Chrome much smoother. <3

I'd like to suggest an option to reorder the elements of the findbar using `order` (considering they're already in a flexbox), specifically putting the `.findbar-label` output before the textbox in order to stop user inputs from being bounced around while typing.

Thanks,
Elliott

**Comment by pointydev** [comment]
Some modifications I've made, just plastered at the end of your CSS, feel free to use as you see fit:
```css
/* Reorder findbar elements to prevent bouncing while typing */
findbar checkbox {
    order: 0;
}
findbar checkbox:last-of-type {
    margin-inline-end: 4px!important;
}
findbar .findbar-label {
    order: 1;
    margin-inline-start: 4px!important;
    margin-inline-end: 4px!important;
}
findbar [anonid="findbar-textbox-wrapper"] {
    order: 2;
    margin-inline-start: 4px!important;
}

/* Hide search modifiers when not hovering */
findbar:not(:hover) checkbox {
    display: none;
}
```
![image](https://github.com/ravindUwU/firefox-refined-findbar/assets/22241432/430a71b5-f432-4bd9-a05a-b6bf13a2aeac)
![image](https://github.com/ravindUwU/firefox-refined-findbar/assets/22241432/146f9735-5f57-4d61-ad4a-9da031719ba2)
![image](https://github.com/ravindUwU/firefox-refined-findbar/assets/22241432/52d8afc4-0641-4e5f-bd09-d0eed1dad782)
![image](https://github.com/ravindUwU/firefox-refined-findbar/assets/22241432/b89b1ff4-1ee2-423e-9287-70467293e9c3)
