### ISSUE TITLE
Ability to remove Close button?

### ISSUE THREAD

**Issue by csmarshall** [ravindUwU/firefox-refined-findbar#4]
Can we add:
1) Ability to remove the close "X"?
2) #5

**Comment by csmarshall** [comment]
This works for me for removing the close button

```css
findbar .close-icon {
  visibility: collapse !important;
}
```
